package com.myorg.game_bj.model.card;

import lombok.Getter;

import static com.myorg.game_bj.model.card.Weight.*;
import static com.myorg.game_bj.model.card.Suit.*;

@Getter
public enum CardType {
    TWO_OF_CLUBS(CLUBS, TWO),
    THREE_OF_CLUBS(CLUBS, THREE),
    FOUR_OF_CLUBS(CLUBS, FOUR),
    FIVE_OF_CLUBS(CLUBS, FIVE),
    SIX_OF_CLUBS(CLUBS, SIX),
    SEVEN_OF_CLUBS(CLUBS, SEVEN),
    EIGHT_OF_CLUBS(CLUBS, EIGHT),
    NINE_OF_CLUBS(CLUBS, NINE),
    TEN_OF_CLUBS(CLUBS, TEN),
    JACK_OF_CLUBS(CLUBS, JACK),
    QUEEN_OF_CLUBS(CLUBS, QUEEN),
    KING_OF_CLUBS(CLUBS, KING),
    ACE_OF_CLUBS(CLUBS, ACE),

    TWO_OF_DIAMONDS(DIAMONDS, TWO),
    THREE_OF_DIAMONDS(DIAMONDS, THREE),
    FOUR_OF_DIAMONDS(DIAMONDS, FOUR),
    FIVE_OF_DIAMONDS(DIAMONDS, FIVE),
    SIX_OF_DIAMONDS(DIAMONDS, SIX),
    SEVEN_OF_DIAMONDS(DIAMONDS, SEVEN),
    EIGHT_OF_DIAMONDS(DIAMONDS, EIGHT),
    NINE_OF_DIAMONDS(DIAMONDS, NINE),
    TEN_OF_DIAMONDS(DIAMONDS, TEN),
    JACK_OF_DIAMONDS(DIAMONDS, JACK),
    QUEEN_OF_DIAMONDS(DIAMONDS, QUEEN),
    KING_OF_DIAMONDS(DIAMONDS, KING),
    ACE_OF_DIAMONDS(DIAMONDS, ACE),

    TWO_OF_HEARTS(HEARTS, TWO),
    THREE_OF_HEARTS(HEARTS, THREE),
    FOUR_OF_HEARTS(HEARTS, FOUR),
    FIVE_OF_HEARTS(HEARTS, FIVE),
    SIX_OF_HEARTS(HEARTS, SIX),
    SEVEN_OF_HEARTS(HEARTS, SEVEN),
    EIGHT_OF_HEARTS(HEARTS, EIGHT),
    NINE_OF_HEARTS(HEARTS, NINE),
    TEN_OF_HEARTS(HEARTS, TEN),
    JACK_OF_HEARTS(HEARTS, JACK),
    QUEEN_OF_HEARTS(HEARTS, QUEEN),
    KING_OF_HEARTS(HEARTS, KING),
    ACE_OF_HEARTS(HEARTS, ACE),

    TWO_OF_SPADES(SPADES, TWO),
    THREE_OF_SPADES(SPADES, THREE),
    FOUR_OF_SPADES(SPADES, FOUR),
    FIVE_OF_SPADES(SPADES, FIVE),
    SIX_OF_SPADES(SPADES, SIX),
    SEVEN_OF_SPADES(SPADES, SEVEN),
    EIGHT_OF_SPADES(SPADES, EIGHT),
    NINE_OF_SPADES(SPADES, NINE),
    TEN_OF_SPADES(SPADES, TEN),
    JACK_OF_SPADES(SPADES, JACK),
    QUEEN_OF_SPADES(SPADES, QUEEN),
    KING_OF_SPADES(SPADES, KING),
    ACE_OF_SPADES(SPADES, ACE);

    private final Suit suit;
    private final Weight weight;

    private CardType(Suit suit, Weight weight) {
        this.suit = suit;
        this.weight = weight;
    }

    @Override
    public String toString() {
        return this.weight + ": " + this.suit;
    }
}
